"""empty message

Revision ID: cf476b394906
Revises: 
Create Date: 2026-07-31 10:40:21.247314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf476b394906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minecraft_server',
    sa.Column('server_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('client_json_file_id', sa.String(length=256), nullable=False),
    sa.Column('modded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('minecraft_modpack',
    sa.Column('modpack_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['minecraft_server.server_id'], ),
    sa.PrimaryKeyConstraint('modpack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minecraft_modpack')
    op.drop_table('minecraft_server')
    op.drop_table('admin')
    # ### end Alembic commands ###
