# Generated by Django 6.0.7 on 2026-07-30 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCServer',
            fields=[
                ('server_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('client_json_url', models.URLField()),
                ('client_json_size', models.BigIntegerField()),
                ('modded', models.BooleanField()),
            ],
            options={
                'db_table': 'mc_server',
            },
        ),
        migrations.CreateModel(
            name='MCModPack',
            fields=[
                ('modpack_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('url', models.URLField()),
                ('size', models.BigIntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minecraft.mcserver')),
            ],
            options={
                'db_table': 'mc_modpack',
            },
        ),
    ]
